/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor;

/**
 *
 * @author student
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        toolBar = new javax.swing.JToolBar();
        buttonNewFile = new javax.swing.JButton();
        buttonOpenFile = new javax.swing.JButton();
        buttonSaveFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        statusBar = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemNewFile = new javax.swing.JMenuItem();
        itemOpenFile = new javax.swing.JMenuItem();
        itemSaveFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemFileInfo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemCloseWindow = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        itemCut = new javax.swing.JMenuItem();
        itemCopy = new javax.swing.JMenuItem();
        itemPaste = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemFind = new javax.swing.JMenuItem();
        itemReplace = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemSelectAll = new javax.swing.JMenuItem();
        menuSetting = new javax.swing.JMenu();
        itemView = new javax.swing.JMenu();
        itemToolBar = new javax.swing.JCheckBoxMenuItem();
        itemStatusBar = new javax.swing.JCheckBoxMenuItem();
        itemBackgroundColor = new javax.swing.JMenuItem();
        itemFont = new javax.swing.JMenuItem();
        itemCharCode = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBar.setRollover(true);

        buttonNewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/new.png"))); // NOI18N
        buttonNewFile.setText("Nový");
        buttonNewFile.setFocusable(false);
        buttonNewFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNewFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewFileActionPerformed(evt);
            }
        });
        toolBar.add(buttonNewFile);

        buttonOpenFile.setIcon(new javax.swing.ImageIcon("D:\\studenti\\IT3\\havranek\\pcv\\Editor\\ikony\\open.png")); // NOI18N
        buttonOpenFile.setText("Otevřít");
        buttonOpenFile.setFocusable(false);
        buttonOpenFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOpenFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(buttonOpenFile);

        buttonSaveFile.setIcon(new javax.swing.ImageIcon("D:\\studenti\\IT3\\havranek\\pcv\\Editor\\ikony\\save.png")); // NOI18N
        buttonSaveFile.setText("Uložit");
        buttonSaveFile.setFocusable(false);
        buttonSaveFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSaveFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(buttonSaveFile);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout statusBarLayout = new javax.swing.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        menuFile.setText("Soubor");

        itemNewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        itemNewFile.setIcon(new javax.swing.ImageIcon("D:\\studenti\\IT3\\havranek\\pcv\\Editor\\ikony\\new-small.png")); // NOI18N
        itemNewFile.setText("Nový");
        itemNewFile.setToolTipText("");
        itemNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNewFileActionPerformed(evt);
            }
        });
        menuFile.add(itemNewFile);

        itemOpenFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemOpenFile.setIcon(new javax.swing.ImageIcon("D:\\studenti\\IT3\\havranek\\pcv\\Editor\\ikony\\open-small.png")); // NOI18N
        itemOpenFile.setText("Otevřít...");
        itemOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOpenFileActionPerformed(evt);
            }
        });
        menuFile.add(itemOpenFile);

        itemSaveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemSaveFile.setIcon(new javax.swing.ImageIcon("D:\\studenti\\IT3\\havranek\\pcv\\Editor\\ikony\\save-small.png")); // NOI18N
        itemSaveFile.setText("Uložit...");
        itemSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveFileActionPerformed(evt);
            }
        });
        menuFile.add(itemSaveFile);
        menuFile.add(jSeparator1);

        itemFileInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        itemFileInfo.setText("Informace o souboru");
        menuFile.add(itemFileInfo);
        menuFile.add(jSeparator2);

        itemCloseWindow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itemCloseWindow.setText("Konec");
        itemCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCloseWindowActionPerformed(evt);
            }
        });
        menuFile.add(itemCloseWindow);

        jMenuBar1.add(menuFile);

        menuEdit.setText("Úpravy");

        itemCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        itemCut.setText("Vyjmout");
        menuEdit.add(itemCut);

        itemCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemCopy.setText("Kopírovat");
        menuEdit.add(itemCopy);

        itemPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        itemPaste.setText("Vložit");
        menuEdit.add(itemPaste);
        menuEdit.add(jSeparator3);

        itemFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemFind.setText("Hledat...");
        menuEdit.add(itemFind);

        itemReplace.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        itemReplace.setText("Nahradit...");
        menuEdit.add(itemReplace);
        menuEdit.add(jSeparator4);

        itemSelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemSelectAll.setText("Vybrat vše");
        menuEdit.add(itemSelectAll);

        jMenuBar1.add(menuEdit);

        menuSetting.setText("Nastavení");

        itemView.setText("Zobrazení");

        itemToolBar.setSelected(true);
        itemToolBar.setText("Panel nástrojů");
        itemToolBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemToolBarActionPerformed(evt);
            }
        });
        itemView.add(itemToolBar);

        itemStatusBar.setSelected(true);
        itemStatusBar.setText("Stavový řádek");
        itemStatusBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStatusBarActionPerformed(evt);
            }
        });
        itemView.add(itemStatusBar);

        menuSetting.add(itemView);

        itemBackgroundColor.setText("Barva pozadí...");
        menuSetting.add(itemBackgroundColor);

        itemFont.setText("Písmo...");
        menuSetting.add(itemFont);

        itemCharCode.setText("Kódování znaků");

        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("UTF-8");
        itemCharCode.add(jRadioButtonMenuItem1);

        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("Windows 1250");
        itemCharCode.add(jRadioButtonMenuItem2);

        buttonGroup1.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("ISO-8859-2");
        itemCharCode.add(jRadioButtonMenuItem3);

        menuSetting.add(itemCharCode);

        jMenuBar1.add(menuSetting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNewFileActionPerformed

    private void itemNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNewFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNewFileActionPerformed

    private void itemOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOpenFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemOpenFileActionPerformed

    private void itemSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSaveFileActionPerformed

    private void itemCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCloseWindowActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemCloseWindowActionPerformed

    private void itemToolBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemToolBarActionPerformed
        if(toolBar.isVisible()){
            toolBar.setVisible(false);
        }else{
            toolBar.setVisible(true);
        }
    }//GEN-LAST:event_itemToolBarActionPerformed

    private void itemStatusBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStatusBarActionPerformed
        if(statusBar.isVisible()){
            statusBar.setVisible(false);
        }else{
            statusBar.setVisible(true);
        }
    }//GEN-LAST:event_itemStatusBarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonNewFile;
    private javax.swing.JButton buttonOpenFile;
    private javax.swing.JButton buttonSaveFile;
    private javax.swing.JMenuItem itemBackgroundColor;
    private javax.swing.JMenu itemCharCode;
    private javax.swing.JMenuItem itemCloseWindow;
    private javax.swing.JMenuItem itemCopy;
    private javax.swing.JMenuItem itemCut;
    private javax.swing.JMenuItem itemFileInfo;
    private javax.swing.JMenuItem itemFind;
    private javax.swing.JMenuItem itemFont;
    private javax.swing.JMenuItem itemNewFile;
    private javax.swing.JMenuItem itemOpenFile;
    private javax.swing.JMenuItem itemPaste;
    private javax.swing.JMenuItem itemReplace;
    private javax.swing.JMenuItem itemSaveFile;
    private javax.swing.JMenuItem itemSelectAll;
    private javax.swing.JCheckBoxMenuItem itemStatusBar;
    private javax.swing.JCheckBoxMenuItem itemToolBar;
    private javax.swing.JMenu itemView;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuSetting;
    private javax.swing.JPanel statusBar;
    private javax.swing.JTextArea textArea;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
