/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cars;

import cars.Car.Size;
import javax.swing.JDialog;

/**
 *
 * @author Dan
 */
public class CarDialog extends javax.swing.JDialog {

    private Car car;
    private String actionButton = "Storno";
    
    public CarDialog(java.awt.Frame parent, boolean modal, Car car){
        super(parent, modal);
        initComponents();
        this.car = car;
        nameTextField.setText(car.getName());
        yearSpinner.setValue(car.getYear());
        if(car.getSize() == Size.Small){
            smallButton.setSelected(true);
        }else if(car.getSize() == Size.Medium){
            mediumButton.setSelected(true);
        }
        else{
            bigButton.setSelected(true);
        }
        consumptionSpinner.setValue(car.getConsumption());
        speedSlider.setValue((int)(car.getSpeed()));
    }
    
    public Car getCar(){
        this.car.setName(nameTextField.getText());
        this.car.setYear((int)yearSpinner.getValue());
        this.car.setConsumption((int)consumptionSpinner.getValue());
        this.car.setSpeed((int)speedSlider.getValue());
        return this.car;
    }
    
    
    public String showDialog(){
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setVisible(true);
        return actionButton;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeButtonGroup = new javax.swing.ButtonGroup();
        nameTextField = new javax.swing.JTextField();
        heading = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        smallButton = new javax.swing.JRadioButton();
        mediumButton = new javax.swing.JRadioButton();
        bigButton = new javax.swing.JRadioButton();
        consumptionLabel = new javax.swing.JLabel();
        consumptionSpinner = new javax.swing.JSpinner();
        speedLabel = new javax.swing.JLabel();
        speedValue = new javax.swing.JLabel();
        speedSlider = new javax.swing.JSlider();
        yearSpinner = new javax.swing.JSpinner();
        okButton = new javax.swing.JButton();
        stornoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        heading.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        heading.setText("Details");

        nameLabel.setText("Name");

        yearLabel.setText("Year of manufacture");

        sizeLabel.setText("Size");

        sizeButtonGroup.add(smallButton);
        smallButton.setText("Small");

        sizeButtonGroup.add(mediumButton);
        mediumButton.setSelected(true);
        mediumButton.setText("Medium");

        sizeButtonGroup.add(bigButton);
        bigButton.setText("Big");

        consumptionLabel.setText("Consumption");

        speedLabel.setText("Top speed");

        speedValue.setText("200");

        speedSlider.setMinimum(50);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        stornoButton.setText("Storno");
        stornoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stornoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel)
                            .addComponent(yearLabel)
                            .addComponent(sizeLabel)
                            .addComponent(consumptionLabel)
                            .addComponent(speedLabel)
                            .addComponent(okButton))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stornoButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(smallButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mediumButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bigButton))
                            .addComponent(consumptionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(speedValue)
                                .addGap(18, 18, 18)
                                .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(yearSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {consumptionSpinner, nameTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLabel)
                    .addComponent(smallButton)
                    .addComponent(mediumButton)
                    .addComponent(bigButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consumptionLabel)
                    .addComponent(consumptionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(speedLabel)
                        .addComponent(speedValue))
                    .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(stornoButton))
                .addGap(40, 40, 40))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {consumptionSpinner, nameTextField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {speedSlider, speedValue});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        actionButton = "OK";
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void stornoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stornoButtonActionPerformed
        actionButton = "Storno";
        this.dispose();
    }//GEN-LAST:event_stornoButtonActionPerformed

    
    private void speedStateChanged(javax.swing.event.ChangeEvent evt) {                                    
        speedValue.setText(String.valueOf(speedSlider.getValue()));
    }       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bigButton;
    private javax.swing.JLabel consumptionLabel;
    private javax.swing.JSpinner consumptionSpinner;
    private javax.swing.JLabel heading;
    private javax.swing.JRadioButton mediumButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup sizeButtonGroup;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JRadioButton smallButton;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JLabel speedValue;
    private javax.swing.JButton stornoButton;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables

   
}
